import PublicLayout from "@/components/layouts/PublicLayout";
import Head from "next/head";
import Link from 'next/link'
import {AiOutlineArrowRight} from 'react-icons/ai'
export default function Home() {


  return (
    <PublicLayout>
      <Head>
        <title>Optipos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="min-h-scree">
          <div className="mx-auto max-w-7xl py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
            <div className="lg:grid lg:grid-cols-2 lg:gap-8">
              <div>
                <h2 className="text-3xl font-extrabold mb-10 dark:text-white text-gray-900 sm:text-4xl">
                OptiPOS
                </h2>

                <div>
                   
                  <Link href="pos">
                    <div className="flex items-center">
                    <AiOutlineArrowRight className="mr-2" /> Point of sales System
                    </div>
                  </Link>

                  <Link href="stock">
                    <div className="flex items-center">
                    <AiOutlineArrowRight className="mr-2" /> Stock management
                    </div>
                  </Link>

                  <Link href="sales">
                    <div className="flex items-center">
                    <AiOutlineArrowRight className="mr-2" /> Sales histories
                    </div>
                  </Link>
                </div>
                
              </div>
            </div>

          </div>
        </div>
      </main>
    </PublicLayout>
  );
}
